### ISSUE TITLE
Error in MCPE version 0.15.10

### ISSUE THREAD

**Issue by ImNotDeveloper** [brandon15811/Minecraft-PE-Proxy#7]
The proxy works but not at the same time, when a user tries to enter, it does not let him and the proxy closes with the following error

> events.js:183
      throw er; // Unhandled 'error' event
      Error [ERR_SOCKET_CANNOT_SEND]: Unable to send data
    at Socket.onListenError (dgram.js:362:22)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at _handle.lookup (dgram.js:267:14)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by enricoangelon** [comment]
The proxy is about 8 years ago...
